# Generated by Django 4.1.6 on 2023-02-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.FloatField(max_length=10)),
                ('ancho', models.FloatField(max_length=10)),
                ('largo', models.FloatField(max_length=10)),
            ],
        ),
    ]
